name: questions_200
description: 200 questions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^10.1.2
  clipboard: ^0.1.3
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  flutter_material_color_picker: ^1.2.0
  hive_flutter: ^1.1.0
  wakelock_plus: ^1.2.8
  html: ^0.15.4
  responsive_builder: ^0.7.1
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
