name: questions_200
description: 200 questions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  path: ^1.8.3
  flutter_html: ^3.0.0-beta.2
  share_plus: ^9.0.0
  clipboard: ^0.1.3
  page_view_dot_indicator: ^2.3.0
  flutter_slidable: ^3.1.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  flutter_material_color_picker: ^1.2.0
  hive_flutter: ^2.0.0-dev
  wakelock_plus: ^1.2.5
  html: ^0.15.4
  responsive_builder: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
